-- ============================================================================
-- Drishti — Supabase schema, RLS, and RPC functions
-- Run this in the Supabase SQL editor (project dtqbturxigckqiqfzdnb).
-- Mirrors the legacy SQLite schema from app.py so the serverless PWA can
-- talk to Supabase directly via @supabase/supabase-js.
-- ============================================================================

create extension if not exists pg_trgm;
create extension if not exists pgcrypto;

-- ─── Roles / profiles ───────────────────────────────────────────────────────
-- NOTE: the profiles table already exists in this project with columns
-- (id uuid, role <enum: admin|volunteer|pre_registree>, full_name text,
-- created_at timestamptz). We keep that shape; the "family" portal maps to the
-- pre_registree role. This block is a no-op when the table already exists.
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  full_name  text,
  role       text not null default 'pre_registree',
  created_at timestamptz default now()
);

-- Auto-create a profile row on new auth user.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
          coalesce((new.raw_user_meta_data->>'role')::text, 'pre_registree'))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ─── Core data tables ─────────────────────────────────────────────────────
create table if not exists public.missing_persons (
  case_id              text primary key,
  reported_at          text,
  missing_person_name  text,
  gender               text,
  age_band             text,
  state                text,
  district             text,
  language             text,
  last_seen_location   text,
  reporting_center     text,
  reporter_mobile      text,
  physical_description text,
  status               text,
  resolution_hours     real,
  is_duplicate_report  int,
  remarks              text
);
create index if not exists idx_mp_status on public.missing_persons(status);
create index if not exists idx_mp_name_trgm on public.missing_persons using gin (missing_person_name gin_trgm_ops);

create table if not exists public.found_persons (
  id                   bigint generated by default as identity primary key,
  found_at             text,
  found_location       text,
  reporting_center     text,
  person_name          text,
  gender               text,
  age_band             text,
  state                text,
  district             text,
  language             text,
  physical_description text,
  contact_mobile       text,
  status               text default 'Pending',
  matched_case_id      text,
  remarks              text,
  photo                text
);

create table if not exists public.report_missing (
  id                    bigint generated by default as identity primary key,
  reported_at           text,
  person_name           text,
  gender                text,
  age_band              text,
  state                 text,
  district              text,
  language              text,
  last_seen_location    text,
  last_seen_time        text,
  physical_description  text,
  photo                 text,
  aadhaar_last4         text,
  reporter_name         text,
  reporter_mobile       text,
  reporter_relationship text,
  special_needs         text,
  status                text default 'Searching',
  matched_found_id      bigint
);

create table if not exists public.callback_requests (
  id              bigint generated by default as identity primary key,
  found_person_id bigint,
  requested_at    text default now()::text,
  status          text default 'pending'
);

create table if not exists public.cctv (
  camera_id text primary key, longitude real, latitude real
);
create table if not exists public.zones (
  zone_name text primary key, centroid_lat real, centroid_lng real, approx_boundary_points int
);
create table if not exists public.police_stations (
  station_name text primary key, longitude real, latitude real
);
create table if not exists public.chokepoints (
  location_name text primary key, category text, longitude real, latitude real
);

-- ─── Row Level Security ───────────────────────────────────────────────────
alter table public.profiles          enable row level security;
alter table public.missing_persons   enable row level security;
alter table public.found_persons      enable row level security;
alter table public.report_missing     enable row level security;
alter table public.callback_requests  enable row level security;
alter table public.cctv               enable row level security;
alter table public.zones              enable row level security;
alter table public.police_stations    enable row level security;
alter table public.chokepoints        enable row level security;

-- profiles: a signed-in user can read profiles (role lookup), update own row
drop policy if exists p_profiles_sel on public.profiles;
create policy p_profiles_sel on public.profiles for select to authenticated using (true);
drop policy if exists p_profiles_upd on public.profiles;
create policy p_profiles_upd on public.profiles for update to authenticated using (id = auth.uid());

-- missing_persons: public read; authenticated write (report-found matching/admin updates)
drop policy if exists p_mp_sel on public.missing_persons;
create policy p_mp_sel on public.missing_persons for select to anon, authenticated using (true);
drop policy if exists p_mp_ins on public.missing_persons;
create policy p_mp_ins on public.missing_persons for insert to authenticated with check (true);
drop policy if exists p_mp_upd on public.missing_persons;
create policy p_mp_upd on public.missing_persons for update to authenticated using (true);

-- found_persons: public read; authenticated insert/update
drop policy if exists p_fp_sel on public.found_persons;
create policy p_fp_sel on public.found_persons for select to anon, authenticated using (true);
drop policy if exists p_fp_ins on public.found_persons;
create policy p_fp_ins on public.found_persons for insert to authenticated with check (true);
drop policy if exists p_fp_upd on public.found_persons;
create policy p_fp_upd on public.found_persons for update to authenticated using (true);

-- report_missing: authenticated read + insert (family/admin)
drop policy if exists p_rm_sel on public.report_missing;
create policy p_rm_sel on public.report_missing for select to authenticated using (true);
drop policy if exists p_rm_ins on public.report_missing;
create policy p_rm_ins on public.report_missing for insert to authenticated with check (true);

-- callback_requests: anyone may request
drop policy if exists p_cb_ins on public.callback_requests;
create policy p_cb_ins on public.callback_requests for insert to anon, authenticated with check (true);

-- reference geo tables: public read
do $$
declare t text;
begin
  foreach t in array array['cctv','zones','police_stations','chokepoints'] loop
    execute format('drop policy if exists p_%1$s_sel on public.%1$s;', t);
    execute format('create policy p_%1$s_sel on public.%1$s for select to anon, authenticated using (true);', t);
  end loop;
end $$;
